# Generated by Django 2.2.2 on 2019-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField()),
                ('name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=32)),
                ('reservation_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TB_ORDER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=32)),
                ('menu_size', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'TB_ORDER_DETAIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbShopBusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(blank=True, max_length=10, null=True)),
                ('business_name', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'TB_SHOP_BUSINESS_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbShopInfo',
            fields=[
                ('uid', models.CharField(max_length=32)),
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=32)),
                ('shop_tel', models.CharField(max_length=32)),
                ('business_hours', models.CharField(max_length=32)),
                ('personal_day', models.CharField(max_length=32)),
                ('introduction', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TB_SHOP_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbShopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=32)),
                ('menu_size', models.CharField(blank=True, max_length=32, null=True)),
                ('hotorcold', models.IntegerField(blank=True, null=True)),
                ('menu_price', models.IntegerField()),
            ],
            options={
                'db_table': 'TB_SHOP_MENU',
                'managed': False,
            },
        ),
    ]
